// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcogjuhgxgoebedzhmkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjb2dqdWhneGdvZWJlZHpobWtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMjI4MzgsImV4cCI6MjA2NTU5ODgzOH0.AOpNa-pLS4wxCilQTSZX0EI_yVqOeO6Xr2LRPX2O5hs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);